# Generated by Django 3.1.4 on 2020-12-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201217_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message_text',
        ),
    ]
